pipeline {
   agent any
   tools {
     maven "MAVEN3"
     jdk "OpenJDK8"
 }

 stages {
   stage('Fetch code'){
     steps {
       git branch: 'docker', url: 'https://github.com/SachinMehta-PB/vprofile-project.git'
     }
   }

   stage('Test'){
     steps {
       sh 'mvn test'
     }
   }
 }
}
