pipeline {
   agent any
   tools {
     maven "MAVEN3"
     jdk "OpenJDK8"
 }

 stages {
   stage('Fetch code'){
     steps {
       git branch: 'docker', url: 'https://github.com/SachinMehta-PB/vprofile-project.git'
     }
   }

   stage('Test'){
     steps {
       sh 'mvn test'
     }
   }

   stage ('CODE ANALYSIS WITH CHECKSTYLE'){
           steps {
               sh 'mvn checkstyle:checkstyle'
           }
           post {
               success {
                   echo 'Generated Analysis Result'
               }
           }
       }


   stage('build && SonarQube analysis') {
           environment {
            scannerHome = tool 'sonar4.7'
         }
           steps {
               withSonarQubeEnv('sonar') {
                sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                  -Dsonar.projectName=vprofile-repo \
                  -Dsonar.projectVersion=1.0 \
                  -Dsonar.sources=src/ \
                  -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                  -Dsonar.junit.reportsPath=target/surefire-reports/ \
                  -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                  -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
               }
           }
       }

    

 }
}
